version: '3.8'
services:
  ads:
    image: rodig03/revive-adserver
    ports:
      - 4000:80
    networks:
      - net
    volumes:
      - ./adserver:/var/www/html
      - ./docker/revive/config/constants.php:/var/www/html/config/constants.php
      - ./docker/revive/lib/templates/admin/dashboard/grid.html:/var/www/html/lib/templates/admin/dashboard/grid.html
  
  db:
    platform: linux/x86_64
    image: mysql:8.0.26
    ports:
      - 3306:3306
    networks:
      - net
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

networks:
  net:
    ipam:
      driver: default